version: "3.9"

services:
    db:
        image: neo4j:latest
        restart: unless-stopped
        environment:
            NEO4J_AUTH: neo4j/password
            NEO4JLABS_PLUGINS: '["apoc"]'
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - data:/data
    workspace:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/workspace
        command: sleep infinity

volumes:
    data: {}
